name: hw-excess
version: '0.2.0.1'
synopsis: Excess
description: Please see README.md
category: Data, Conduit
author: John Ky
maintainer: newhoggy@gmail.com
copyright: 2016 John Ky
license: BSD3
github: haskell-works/hw-excess
homepage: http://github.com/haskell-works/hw-excess#readme
tested-with: GHC == 8.4.2, GHC == 8.2.2, GHC == 8.0.2, GHC == 7.10.3
extra-source-files:
- README.md
ghc-options: -Wall
dependencies:
- base >=4.8 && <5
- hw-bits >=0.4.0.0 && < 0.8
- hw-prim >=0.4.0.0 && < 0.7
- vector >= 0.12 && < 0.13
library:
  source-dirs: src
  ghc-options:
  - -O2
  - -msse4.2
  exposed-modules:
  - HaskellWorks.Data.Excess
  - HaskellWorks.Data.Excess.Excess0
  - HaskellWorks.Data.Excess.Excess1
  - HaskellWorks.Data.Excess.MinMaxExcess0
  - HaskellWorks.Data.Excess.MinMaxExcess1
  - HaskellWorks.Data.Excess.Triplet
  dependencies:
  - hw-rankselect-base >=0.2.0.0 && < 0.4
  - safe >= 0.2 && < 0.4
  - storable-record >= 0.0.3 && < 0.1
tests:
  hw-excess-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec >= 2.5 && < 2.6
    - hw-excess
    - QuickCheck >= 2.10 && < 2.12
    verbatim:
      build-tool-depends: hspec-discover:hspec-discover
